// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzus5slRbIlZ1isHpTvRVdG18gKxEDCb8',
    appId: '1:837366691306:web:2005651b320b3345652e93',
    messagingSenderId: '837366691306',
    projectId: 'tickets-firebase-aba0a',
    authDomain: 'tickets-firebase-aba0a.firebaseapp.com',
    storageBucket: 'tickets-firebase-aba0a.firebasestorage.app',
    measurementId: 'G-4HTVSFMPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9NwLwhD2JVrzmzJm5NWhTOM5jv7kvns',
    appId: '1:837366691306:android:d42729b06274e244652e93',
    messagingSenderId: '837366691306',
    projectId: 'tickets-firebase-aba0a',
    storageBucket: 'tickets-firebase-aba0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdKT_Pi--LdEMEKcp3j9ufgKZ1UUiN_Xo',
    appId: '1:837366691306:ios:35fbcda00d77fcef652e93',
    messagingSenderId: '837366691306',
    projectId: 'tickets-firebase-aba0a',
    storageBucket: 'tickets-firebase-aba0a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdKT_Pi--LdEMEKcp3j9ufgKZ1UUiN_Xo',
    appId: '1:837366691306:ios:35fbcda00d77fcef652e93',
    messagingSenderId: '837366691306',
    projectId: 'tickets-firebase-aba0a',
    storageBucket: 'tickets-firebase-aba0a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzus5slRbIlZ1isHpTvRVdG18gKxEDCb8',
    appId: '1:837366691306:web:b4a71afb6cc47483652e93',
    messagingSenderId: '837366691306',
    projectId: 'tickets-firebase-aba0a',
    authDomain: 'tickets-firebase-aba0a.firebaseapp.com',
    storageBucket: 'tickets-firebase-aba0a.firebasestorage.app',
    measurementId: 'G-SY603GE567',
  );
}
